apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-ui
  labels:
    app: ui
    tier: frontend
spec:
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        app: ui
        tier: frontend
    spec:
      containers:
      - name: server
        image: hendrax76/karsajobs-ui:latest
        ports:
          - containerPort: 8000
        env:
          - name: VUE_APP_BACKEND
            value: http://$(KARSAJOBS_API_SERVICE_HOST):$(KARSAJOBS_API_SERVICE_PORT)
